<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-05-17T19:58:26 IST" name="Default Suite" finished-at="2022-05-17T19:58:32 IST" duration-ms="5145">
    <groups>
    </groups>
    <test started-at="2022-05-17T19:58:26 IST" name="EveningBatchDemo" finished-at="2022-05-17T19:58:32 IST" duration-ms="5145">
      <class name="testng.extendsreports.ExtendsReportsExample">
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:testng.extendsreports.ExtendsReportsExample@17f62e33]" started-at="2022-05-17T19:58:26 IST" name="beforeTest" finished-at="2022-05-17T19:58:28 IST" duration-ms="1380" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method signature="verifyReport1()[pri:0, instance:testng.extendsreports.ExtendsReportsExample@17f62e33]" started-at="2022-05-17T19:58:28 IST" name="verifyReport1" finished-at="2022-05-17T19:58:28 IST" duration-ms="236" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyReport1 -->
        <test-method signature="verifyReport2()[pri:0, instance:testng.extendsreports.ExtendsReportsExample@17f62e33]" started-at="2022-05-17T19:58:28 IST" name="verifyReport2" finished-at="2022-05-17T19:58:28 IST" duration-ms="52" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
The Value should be match expected [Test] but found [Ganesh]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
The Value should be match expected [Test] but found [Ganesh]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at testng.extendsreports.ExtendsReportsExample.verifyReport2(ExtendsReportsExample.java:39)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyReport2 -->
        <test-method signature="verifyReport3()[pri:0, instance:testng.extendsreports.ExtendsReportsExample@17f62e33]" started-at="2022-05-17T19:58:28 IST" name="verifyReport3" finished-at="2022-05-17T19:58:28 IST" duration-ms="8" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyReport3 -->
        <test-method is-config="true" signature="reportClosed()[pri:0, instance:testng.extendsreports.ExtendsReportsExample@17f62e33]" started-at="2022-05-17T19:58:28 IST" name="reportClosed" finished-at="2022-05-17T19:58:32 IST" duration-ms="3115" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportClosed -->
      </class> <!-- testng.extendsreports.ExtendsReportsExample -->
    </test> <!-- EveningBatchDemo -->
  </suite> <!-- Default Suite -->
</testng-results>
